version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'Harjas1703.'
      MYSQL_DATABASE: 'trading_platform'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Harjas1703.'
    ports:
      - "3307:3306"
